### ISSUE TITLE
What's whitenoise in AR1?

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/TransitionsInTimeseries.jl#40]
I don't understand why there is `_whitenoise` at the end of the function `ar1_whitenoise`. The docstirng also does not describe it. We need to either explain in the docstirng or simplify the function to just `ar1`.

**Comment by Datseris** [comment]
bump @JanJereczek

**Comment by JanJereczek** [comment]
Fixed. "whitenoise" refers to the assumption of a Gaussian noise for the estimation of the AR1 coefficient. This is now specified in the docs.
