### ISSUE TITLE
Convenience functions for plotting

### ISSUE THREAD

**Issue by JanJereczek** [JuliaDynamics/TransitionsInTimeseries.jl#63]
**Is your feature request related to a problem? Please describe.**
Plotting of the results is generic. Therefore providing a convenience function for it would cut down the amount of code needed.

**Describe the solution you'd like**
Rely on CairoMakie and allow something like:
```
plot(results, signif)
```

**Comment by Datseris** [comment]
I added a first draft of these functions here: 

https://github.com/JuliaDynamics/TransitionsInTimeseries.jl/blob/main/ext/TITVisualizations.jl

a new PR needs to document them and add them in the examples in the docs.

**Comment by JanJereczek** [comment]
Thanks for starting this, George! I would mainly suggest one modification. I think we should have a plot with `n+1` rows and `1` column, with `n` the number of indicators. In the first row, we plot the input timeseries and optionally some surrogates in a lighter shading. For the `i+1`-th row, we plot the timeseries of the `i`-th indicator and its change metric.

I think this fits better than what we have so far (plotting all indicators on one axis), since they can have very different orders of magnitude, which is very inconvenient for visualisation.

**Comment by Datseris** [comment]
What about the change metrics? where do you plot those? Or do you suggest that we plot directly the change metrics?

**Comment by JanJereczek** [comment]
Since each indicator has a subplot assigned to it, it is easy to add an axis to each of them to visualise the change metric associated with the indicator. Something like:

```julia
indic_ax = Axis(fig[i, 1], yaxisposition = :left)
chng_ax = Axis(fig[i, 1], yaxisposition = :right)
```

**Comment by Datseris** [comment]
So you mean to plot the indicator timeseries and the change metric timeseries in the _same_ panel? Yes, we can do that.
