### ISSUE TITLE
pvalues counting for surrogate significance is broken

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/TransitionsInTimeseries.jl#65]
Have a look here: 

https://juliadynamics.github.io/TransitionsInTimeseries.jl/dev/examples/logistic/#Significance-via-random-Fourier-surrogates

this exacmple used to be perfectly fine. Now, every single time point gets a significance flag. I believe this is because of our re-worked p-value counting code. That code is also over-engineered. We should simplify it back to its original, most simple possible version, because the performance of this code does not matter at all: it has miniscule impact on overall runtime.

**Comment by JanJereczek** [comment]
I have spotted the error. It came from how we newly handle `nothing` as an indicator. I will PR the fixed code soon!
